// <auto-generated />
namespace SINPE.Empresarial.Infrastructure.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Identity_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Identity_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "202508160927156_Identity_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
