// <auto-generated />
namespace SINPE_Empresarial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ProyectoLau1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProyectoLau1));
        
        string IMigrationMetadata.Id
        {
            get { return "202506230031143_ProyectoLau1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
